---
name: test (pinact)
on: pull_request
permissions: {}
jobs:
  pinact:
    runs-on: ubuntu-24.04
    if: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
